### ISSUE TITLE
As a developer I should be able to refer to documentation in order to understand how to leverage the chaincode starter kit

### ISSUE THREAD

**Issue by sanjayravindraibm** [IBM-Blockchain-Starter-Kit/chaincode-bootstrap#4]
Creating necessary documentation to leverage the automation capabilities of this bootstrap project. This should include the description of any type of input that needs to be provided during the setup of the toolchain. It should also include any additional setup that is required for the pipeline to work properly.

**Comment by yorhodes** [comment]
https://github.com/IBM-Blockchain-Starter-Kit/chaincode-bootstrap/commit/92bc1088a6980280d736ff66400aaeb54228cd51
